"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import lookupresponse as components_lookupresponse
from enum import Enum
from typing import List, Optional


class Type(str, Enum):
    CNAM = 'cnam'


@dataclasses.dataclass
class LookupRequest:
    phone_number: str = dataclasses.field(metadata={'path_param': { 'field_name': 'phone_number', 'style': 'simple', 'explode': False }})
    customer_uuid: str = dataclasses.field(metadata={'header': { 'field_name': 'customer-uuid', 'style': 'simple', 'explode': False }})
    type: Optional[List[Type]] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'type', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class LookupResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    lookup_response: Optional[components_lookupresponse.LookupResponse] = dataclasses.field(default=None)
    r"""OK"""
    

