"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from ding import utils
from enum import Enum
from typing import Optional


class Code(str, Enum):
    r"""A machine-readable code that describes the error."""
    ACCOUNT_INVALID = 'account_invalid'
    APP_REALM_REQUIRE_DEVICE_TYPE = 'app_realm_require_device_type'
    BAD_REQUEST = 'bad_request'
    BLOCKED_NUMBER = 'blocked_number'
    DUPLICATED_FEEDBACK_STATUS = 'duplicated_feedback_status'
    INTERNAL_SERVER_ERROR = 'internal_server_error'
    INVALID_APP_REALM = 'invalid_app_realm'
    INVALID_APP_VERSION = 'invalid_app_version'
    INVALID_AUTH_UUID = 'invalid_auth_uuid'
    INVALID_DEVICE_ID = 'invalid_device_id'
    INVALID_DEVICE_MODEL = 'invalid_device_model'
    INVALID_FEEDBACK_STATUS = 'invalid_feedback_status'
    INVALID_LINE = 'invalid_line'
    INVALID_OS_VERSION = 'invalid_os_version'
    INVALID_PHONE_NUMBER = 'invalid_phone_number'
    INVALID_SENDER_ID = 'invalid_sender_id'
    INVALID_TEMPLATE_ID = 'invalid_template_id'
    NEGATIVE_BALANCE = 'negative_balance'
    NO_ASSOCIATED_AUTH_FOUND = 'no_associated_auth_found'
    SUSPENDED_ACCOUNT = 'suspended_account'
    UNAUTHORIZED_SENDER_ID = 'unauthorized_sender_id'
    UNSUPPORTED_APP_REALM_DEVICE_TYPE = 'unsupported_app_realm_device_type'
    UNSUPPORTED_REGION = 'unsupported_region'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ErrorResponse(Exception):
    code: Optional[Code] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('code'), 'exclude': lambda f: f is None }})
    r"""A machine-readable code that describes the error."""
    message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    r"""A human-readable message that describes the error."""
    doc_url: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('doc_url'), 'exclude': lambda f: f is None }})
    r"""A link to the documentation that describes the error."""
    

    def __str__(self) -> str:
        return utils.marshal_json(self, type(self))
