"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from ding import utils
from enum import Enum
from typing import Optional

class CreateCheckResponseStatus(str, Enum):
    r"""A status representing the result of the check."""
    VALID = 'valid'
    INVALID = 'invalid'
    WITHOUT_ATTEMPT = 'without_attempt'
    RATE_LIMITED = 'rate_limited'
    ALREADY_VALIDATED = 'already_validated'
    EXPIRED_AUTH = 'expired_auth'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateCheckResponse:
    authentication_uuid: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('authentication_uuid'), 'exclude': lambda f: f is None }})
    r"""The UUID of the corresponding authentication."""
    status: Optional[CreateCheckResponseStatus] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status'), 'exclude': lambda f: f is None }})
    r"""A status representing the result of the check."""
    

